### <font color="red"> Numpy is a python library , stands for numerical python. it containd a collection of tools and techniques that can be used to solve on a computer mathematical models of problems

In [2]:
import numpy as np

In [6]:
print(np.__version__)

1.26.4


In [8]:
#printing of the one dimensional array 
a= np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
#printing of the 2nd dimensional arrya
b=np.array([[1,2,3,],[4,5,6]])
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [16]:
#printing of the 3rd dimensional array
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
#dimnesion of the array checking 
print(a.ndim)
print(b.ndim)
print(c.ndim)


1
2
3


### shape - it return the shape of an array in tuple , it can also be used to resize the array 

In [23]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 3)
(2, 2, 2)


### length - it return an array for n dimension , it return size of the first dimension


In [26]:
print(len(a))
print(len(b))
print(len(c))

4
2
2


### dtype = it returns the datatype of an array

In [37]:
d=np.array([1,2,3,4],dtype='complex')
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)
print(d)

int32
int32
int32
complex128
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


### size - it return the total nuber of the element inside the array 

In [40]:
print(a.size)
print(b.size)
print(c.size)

4
6
8


### itemsize- it return elements of an array in bytes size

In [43]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

4
4
4
